# School suspensions and the Chi-Square Test
# First, create and store data in objects
susp.h <- c(39, 114, 19980, 15681, 16, 168, 904) # number suspended
enrl.h <- c(483, 7394, 53238, 131004, 204, 1857, 17372) # number enrolled
barplot(susp.h/enrl.h, names.arg=c("Indian", "Asian", "Black", "Latino", "Pacific", "Multiple", "White")) # visualize by ethnicity

# Create some more data
nots.h <- enrl.h - susp.h # those not suspended
table.h <- cbind(susp.h, nots.h)
rownames(table.h) <- c("Indian", "Asian", "Black", "Latino", "Pacific", "Multiple", "White")
colnames(table.h) <- c("Suspended", "Not")
ftable(table.h) # see a contingency table by ethnicity

# Now observe a margin table (from help docs): ``For a contingency table in array form, compute the sum of table entries for a given index."
margin.table(table.h, margin = 2) # (margin = 1: sum by row; =2: sum by column)

# The way that the chi-square test is calculated, take the proportion generated by the marginal (in this case 17.5%) and then 
# generate expected cell frequencies based on that. The chi-square test is the cell-by-cell sum of the squared difference 
# between the observed and expected cell frequency, divided by the expected cell frequency. 

# In other words, it tests the degree to which individual deviates from the aggregate e.g., if 17.5% of students are suspended, 
# then we should expect 17.5% of each ethnicity suspended significant value means the difference between observed and expected (17.5%) 
# is larger than expected due to chance alone - i.e., ethnicity matters in suspensions

# Actually run the test
chisq.test(table.h) 

# Do we reject the null of independence between ethnicities, or do we fail to reject?
